### ISSUE TITLE
keyword-parser not found on Ubuntu

### ISSUE THREAD

**Issue by revelutions** [rainingclouds/keyword-parser#1]
When I try to use keyword-parser on Ubuntu, I get 'command not found'.

Can you give some more instructions on how to set it up

**Comment by rtdp** [comment]
Need to make sure that `GOPATH/bin` is included in the PATH variable, only then keyword-parser will be accessible.

As described here for all go packages to work - https://github.com/golang/go/wiki/GOPATH#integrating-gopath

**Comment by revelutions** [comment]
Hi Ratnadeep,

I got this working.  However, I am getting an error with rubyvernac.  Btw, I just play around with Ruby on the command line.  I am not using Bundler.

Thanks,
- Nilanjan

[cid:31637b56-36c2-46b2-9d47-282cd7a742a6]

**Comment by revelutions** [comment]
Need to setup the GO environment. 

mkdir ~/.go
echo "GOPATH=$HOME/.go" >> ~/.bashrc
echo "export GOPATH" >> ~/.bashrc
echo "PATH=\$PATH:\$GOPATH/bin # Add GOPATH/bin to PATH for scripting" >> ~/.bashrc
source ~/.bashrc

**Then** download keyword-parser.

What the commands to is setup GOPATH.  Then add GOPATH/bin to PATH.  keyword-parser is donwloaded to GOPATH.

You don't need GOROOT
